<html>
<head><title>login page</title></head>
<body> 

<form name="login_form" method="POST" action="next.asp">

<table width="100%" height="100%" background="images\Fiesta%20Bkgrd.jpg">
<tr height="35%">
<td rowspan="4"><img src="images/TheBlueTopaz.gif" width=400 height=196></td>
<td></td>
<td></td>
</tr>
<tr height="15%">
<td>
<p align="center"><font size="6" color="blue"><i>Existing Custommer</i></font></p>
<td>
<p align="center"><font size="6" color="blue"><i>New Custommer</i></font></p>
</tr>
<tr height="15%">
<td>
<p align="center"><b>Login Id</b>    &nbsp;

<input type="text" name="lid"></p>

<p align="center">

<b>Password</b>    

<input type="password" name="pass">

<br> <br>

&nbsp; &nbsp;  &nbsp; &nbsp; &nbsp; &nbsp;

<input type="submit" value="Login" name="b">  
</td>
<td>
<p align="center"><a href="signup.asp">Sign Me Up</a></p>
</td>
</tr>
<tr height="35%"></tr>

</table>
</form>
</body>
</html>

